config/routes.rb
Rails.application.routes.draw do
  root to: 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: %i[show destroy]

  def index
    @flats = Flat.all
  end

  def show 
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def find_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= form_for(flat) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :address, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :number_of_guests %>
    <%= f.number_field :number_of_guests, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price_per_night %>
    <%= f.number_field :price_per_night, class: 'form-control' %>
  </div>
  <div class="mt-3">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', '#', class: 'btn btn-danger ml-2' %>
  </div>
<% end %>

app/views/flats/index.html.erb
<h1>
    List of all available flats
</h1>

<div class="flats-container">

  <% @flats.each do |flat| %>
    <div class="flat-card">
        <%= link_to flat_path(flat) do %>
          <h2><%= flat.name %></h2>
          <p><%= flat.address %></p>
          <p><%= flat.description %></p>
          <p><%= flat.price_per_night %></p>
          <p><%= flat.number_of_guests %></p>
          <%= link_to "Remove", flat_path(flat),
                method: :delete, 
                data: { confirm: "Are you sure?" },
                class: 'ml-3 text-danger'
            %>
    <% end %>  
  </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<div class="container mt-4">
    <div class="row">
      <div class="col-6 m-auto">
        <div class="flat-form">
          <h1>Add a new Flat</h1>
          <div class="mt-3">
            <%= render "form", flat: @flat %>    
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/flats/show.html.erb
<div
  class="flat_show">
    <%= @flat.name %>
    <%= @flat.address %>
    <%= @flat.description %>
    <%= @flat.price_per_night %>
    <%= @flat.number_of_guests %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnbBatch316</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Simple Airbnb', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ml-auto flex">
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="<%= params[:query] %>">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
          <%= link_to 'Add Flat', new_flat_path, class: 'btn btn-outline-primary my-2 my-sm-0 ml-2' %>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>